// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accept: typeof import('./components/dialogs/Accept.vue')['default']
    AccountItem: typeof import('./components/AccountItem.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Bid: typeof import('./components/dialogs/Bid.vue')['default']
    Burn: typeof import('./components/dialogs/Burn.vue')['default']
    Buy: typeof import('./components/dialogs/Buy.vue')['default']
    CancelBid: typeof import('./components/dialogs/CancelBid.vue')['default']
    CancelSale: typeof import('./components/dialogs/CancelSale.vue')['default']
    CollectionItem: typeof import('./components/CollectionItem.vue')['default']
    Drop: typeof import('./components/self/drop/index.vue')['default']
    FilterAndSort: typeof import('./components/FilterAndSort.vue')['default']
    FollowLoad: typeof import('./components/loading/FollowLoad.vue')['default']
    FollowPopup: typeof import('./components/FollowPopup.vue')['default']
    FullScreen: typeof import('./components/FullScreen.vue')['default']
    Jazzicon: typeof import('./components/components/Jazzicon.vue')['default']
    Load: typeof import('./components/self/drop/load.vue')['default']
    LoadStatus: typeof import('./components/LoadStatus.vue')['default']
    Mint: typeof import('./components/dialogs/Mint.vue')['default']
    NFTItem: typeof import('./components/NFTItem.vue')['default']
    NFTItemLoad: typeof import('./components/self/nftList/NFTItemLoad.vue')['default']
    NftList: typeof import('./components/self/nftList/index.vue')['default']
    NFTPreview: typeof import('./components/NFTPreview.vue')['default']
    NoContent: typeof import('./components/NoContent.vue')['default']
    NoFound: typeof import('./components/NoFound.vue')['default']
    NoticeItem: typeof import('./components/NoticeItem.vue')['default']
    NoticeLoad: typeof import('./components/loading/NoticeLoad.vue')['default']
    Partners: typeof import('./components/self/partners/index.vue')['default']
    Placeholder: typeof import('./components/Placeholder.vue')['default']
    Popular: typeof import('./components/self/recommend/index.vue')['default']
    ProfilePopover: typeof import('./components/ProfilePopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sale: typeof import('./components/dialogs/Sale.vue')['default']
    Share: typeof import('./components/Share.vue')['default']
    Trading: typeof import('./components/self/trading/index.vue')['default']
    Transfer: typeof import('./components/dialogs/Transfer.vue')['default']
    Window: typeof import('./components/Window.vue')['default']
  }
}
